import Image from 'next/image';
import { ArrowDown, MapPin, MessageCircle, PackageCheck, Sprout } from 'lucide-react';

const products = [
  { name: '鸡枞菌', source: '云南当季鲜选', feature: '菌香浓郁，口感鲜嫩', cook: '适合清炒、煲汤、炖鸡', price: '¥168 / 500g', image: 'https://images.unsplash.com/photo-1504544750208-dc0358e63f7f?auto=format&fit=crop&w=900&q=85' },
  { name: '青头菌', source: '昆明木水花市场鲜选', feature: '肉质紧实，清甜回甘', cook: '适合清炒、蒸蛋、煮汤', price: '今日微信咨询', image: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&w=900&q=85' },
  { name: '松茸', source: '香格里拉高山到货', feature: '香气清冽，风味细腻', cook: '适合黄油煎、炖汤、蒸饭', price: '¥399 / 500g', image: 'https://images.unsplash.com/photo-1623681003301-3e8c1c20d1d8?auto=format&fit=crop&w=900&q=85' },
];
const market = [['鸡枞菌','¥168 / 500g','少量到货','清炒、炖鸡'],['青头菌','今日微信咨询','供应充足','清炒、煮汤'],['松茸','¥399 / 500g','需要预订','香煎、炖汤'],['牛肝菌','今日微信咨询','随市场更新','炒饭、意面']];
const trust = [['云南产区鲜选','根据菌季和当天状态进行筛选'],['每日市场更新','价格、品种和库存随市场变化'],['昆明同城配送','具体配送范围和时效微信确认']];

export default function Home() { return <main className="overflow-x-hidden bg-[#f7f4ec]">
  <section id="home" className="relative min-h-[670px] overflow-hidden bg-forest-900 text-white sm:min-h-[720px]">
    <Image priority fill sizes="100vw" src="https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=2000&q=90" alt="云南山野森林" className="object-cover opacity-55"/>
    <div className="absolute inset-0 bg-gradient-to-b from-black/20 via-forest-900/15 to-forest-900"/>
    <nav className="container relative flex items-center justify-between gap-3 py-4 sm:py-6"><a href="#home" className="shrink-0 font-serif text-xl tracking-[.18em] sm:text-2xl">菌鲜到</a><div className="hidden items-center gap-6 text-sm text-white/80 md:flex"><a href="#home">首页</a><a href="#fresh">今日鲜菌</a><a href="#market">今日行情</a><a href="#story">鲜菌故事</a></div><a href="#wechat" className="shrink-0 rounded-full border border-white/50 px-3.5 py-2 text-xs sm:text-sm">微信咨询</a></nav>
    <div className="container relative pt-20 sm:pt-28"><p className="text-xs font-semibold tracking-[.24em] text-amber-200">KUNMING · WILD MUSHROOMS</p><h1 className="mt-4 max-w-[345px] font-serif text-[40px] leading-[1.12] tracking-tight sm:max-w-3xl sm:text-7xl">云南野生菌<br/><span className="text-amber-100">每日鲜选 · 昆明直送</span></h1><p className="mt-5 max-w-md text-sm leading-7 text-white/85 sm:mt-7 sm:text-base sm:leading-8">深入云南菌市，精选当季新鲜野生菌。<br className="hidden sm:block"/>每日更新上市品种、菌价和库存，让山野鲜味更快到达餐桌。</p><div className="mt-8 flex flex-wrap gap-3"><a href="#fresh" className="rounded-full bg-amber-100 px-5 py-3 text-sm font-semibold text-forest-900">查看今日鲜菌</a><a href="#wechat" className="rounded-full border border-white/50 px-5 py-3 text-sm">微信咨询</a></div></div>
  </section>
  <section className="relative -mt-6 px-4 sm:-mt-8"><div className="container grid gap-3 md:grid-cols-3">{trust.map(([title,text],i)=><article key={title} className="rounded-2xl bg-white p-5 shadow-soft"><div className="mb-3 text-forest-500">{i===0?<Sprout size={21}/>:i===1?<PackageCheck size={21}/>:<MapPin size={21}/>}</div><h2 className="font-serif text-xl">{title}</h2><p className="mt-2 text-sm leading-6 text-stone-500">{text}</p></article>)}</div></section>
  <section id="fresh" className="container py-16 sm:py-24"><p className="text-xs font-semibold tracking-[.2em] text-forest-500">TODAY'S FRESH PICKS</p><h2 className="mt-3 font-serif text-3xl sm:text-4xl">今天，从菌市带回来的鲜味</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-stone-500">野生菌价格随天气、产量和当天市场情况变化，实际价格请以微信确认结果为准。</p><div className="mt-8 grid gap-5 md:grid-cols-3">{products.map(p=><article key={p.name} className="overflow-hidden rounded-2xl bg-white shadow-soft"><div className="relative h-64"><Image fill sizes="(max-width: 768px) 100vw, 33vw" src={p.image} alt={p.name} className="object-cover"/></div><div className="p-5"><p className="text-xs text-forest-500">{p.source}</p><h3 className="mt-2 font-serif text-2xl">{p.name}</h3><p className="mt-4 text-sm text-stone-700">{p.feature}</p><p className="mt-1 text-sm text-stone-500">{p.cook}</p><p className="mt-5 font-semibold text-forest-700">今日参考价：{p.price}</p><p className="mt-2 text-xs leading-5 text-stone-400">野生菌价格随天气、产量和当天市场情况变化，请以微信确认结果为准。</p><a href="#wechat" className="mt-5 block rounded-xl border border-forest-500 py-3 text-center text-sm font-medium text-forest-700">咨询当天库存</a></div></article>)}</div></section>
  <section id="market" className="bg-[#e8e7d8]"><div className="container py-16 sm:py-24"><p className="text-xs font-semibold tracking-[.2em] text-forest-500">MARKET UPDATE</p><h2 className="mt-3 font-serif text-3xl sm:text-4xl">今日菌市行情</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-stone-600">野生菌价格和供应量每天都会变化，以下内容作为当天市场参考，具体品相、规格和库存请微信确认。</p><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{market.map(([name,price,status,cook])=><article key={name} className="rounded-2xl bg-[#f7f4ec] p-5"><h3 className="font-serif text-xl">{name}</h3><p className="mt-4 text-sm font-semibold text-forest-700">{price}</p><p className="mt-3 text-xs text-stone-500">供应状态 · {status}</p><p className="mt-1 text-xs text-stone-500">适合 · {cook}</p></article>)}</div><a href="#wechat" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-forest-700">微信确认今日品相与库存 <ArrowDown size={15}/></a></div></section>
  <section id="story" className="container py-16 sm:py-24"><div className="grid gap-9 md:grid-cols-2 md:items-center"><div><p className="text-xs font-semibold tracking-[.2em] text-forest-500">FROM MARKET TO TABLE</p><h2 className="mt-3 font-serif text-3xl leading-tight sm:text-4xl">一颗菌子的鲜味旅程</h2><p className="mt-6 text-sm leading-7 text-stone-600">云南的野生菌随着天气、海拔和菌季不断变化。</p><p className="mt-4 text-sm leading-7 text-stone-600">我们根据当天到货情况，查看菌子的完整度、新鲜度和品相，再选择适合家庭餐桌和餐饮使用的菌子。</p><p className="mt-4 text-sm leading-7 text-stone-600">这里不追求长期库存，而是跟随菌季，把当天状态更好的鲜菌分享给真正喜欢云南味道的人。</p></div><div className="grid grid-cols-2 gap-3"><div className="relative col-span-2 h-52 overflow-hidden rounded-2xl"><Image fill sizes="(max-width:768px) 100vw, 50vw" src="https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80" alt="云南山林" className="object-cover"/></div><div className="rounded-2xl bg-[#e8e7d8] p-5 text-sm text-forest-700">云南山林<br/><span className="text-xs text-stone-500">随菌季而来</span></div><div className="rounded-2xl bg-forest-900 p-5 text-sm text-white">市场鲜选<br/><span className="text-xs text-white/65">查看品相与状态</span></div></div></div></section>
  <section id="wechat" className="bg-[#604833] text-white"><div className="container grid gap-9 py-16 sm:py-24 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-xs font-semibold tracking-[.2em] text-amber-200">WECHAT CONTACT</p><h2 className="mt-3 font-serif text-4xl">加入云南鲜菌微信</h2><p className="mt-5 max-w-lg text-sm leading-7 text-white/80">每天分享当季鲜菌、市场变化和到货情况。</p><ul className="mt-6 grid gap-2 text-sm text-white/85 sm:grid-cols-2"><li>· 今日菌价更新</li><li>· 当季新品提醒</li><li>· 少量鲜菌预订</li><li>· 昆明配送咨询</li><li>· 野生菌食用建议</li></ul><p className="mt-7 text-xs leading-6 text-amber-100/80">长按识别二维码，或保存图片后使用微信扫码添加。</p></div><div className="justify-self-center rounded-2xl bg-white p-3 shadow-soft"><Image src="/images/wechat-qr.png" alt="微信二维码：希西" width={300} height={444} className="h-auto w-[260px] max-w-[70vw] object-contain sm:w-[300px]" priority/></div></div></section>
  <a href="#wechat" aria-label="微信咨询" className="fixed bottom-5 right-4 z-20 inline-flex items-center gap-2 rounded-full bg-forest-700 px-4 py-3 text-sm font-medium text-white shadow-lg md:hidden"><MessageCircle size={18}/>微信咨询</a>
  <footer className="bg-[#38281d] px-5 py-8 text-center text-xs leading-6 text-white/55">云南野生菌鲜选<br/>昆明同城配送范围和当天库存请通过微信咨询<br/>© 2026 菌鲜到</footer>
</main> }
